version: '3'

vars:
  ENTRYPOINT: ./cmd/cleaner/android-cleaner.go
  BINARY: android-cleaner

tasks:
  run:
    cmds:
      - go run {{.ENTRYPOINT}}

  build:
    cmds:
      - go build {{.ENTRYPOINT}}    
      
  clean:
    cmds:
      - rm -vf ./{{.BINARY}}  
