package main

import (
	"android-cleaner/src/adb"
	"android-cleaner/src/command"
	"android-cleaner/src/input"
	"flag"
	"fmt"
	"os"
)

func main() {
	filepath := flag.String("file", "packages.txt", "File containing package names (generated by 'Package Names'")
	flag.Parse()

	file, err := os.Open(*filepath)
	defer file.Close()
	if err != nil {
		fmt.Println("Invalid or missing input file provided")
		return
	}

	packages, err := input.Cleanse(file)
	if err != nil {
		fmt.Println(err)
		return
	}

	for _, pkg := range packages {
		fmt.Printf("Disabling Package: %s ", pkg)
		err := adb.DisablePackage(pkg, command.Executor)

		if err != nil {
			fmt.Printf("\t[Failed]\n\nError: %v\n", err)
		} else {
			fmt.Printf("[Done]\n")
		}
	}
}
