package main

import (
	//"android-cleaner/pkg/adb"
	//"android-cleaner/pkg/command"
	"android-cleaner/pkg/input"
	"errors"
	"flag"
	"fmt"
	"os"
)

func run() error {
	filepath := flag.String("file", "packages.txt", "File containing package names (generated by 'Package Names'")
	flag.Parse()

	file, err := os.Open(*filepath)
	defer file.Close()
	if err != nil {
		return errors.New("Invalid or missing input file provided")
	}

	lines, err := input.ReadContent(file)
	if err != nil {
		return err
	}

	packages, err := input.Cleanse(lines)
	if err != nil {
		return err
	}

	for _, pkg := range packages {
		fmt.Printf("[Disabling] %s\n", pkg)
		/*
			if err := adb.DisablePackage(pkg, command.Executor); err != nil {
				fmt.Printf("[Error] %s: %s\n", pkg, err.Error())
			}
		*/
	}

	return nil
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err.Error())
		os.Exit(1)
	}
}
